language: php

sudo: false

cache:
    directories:
        - vendor
        - $HOME/.composer/cache

php:
    - 5.3
    - 5.4
    - 5.5
    - 5.6
    - 7.0
    - hhvm

env:
    - dependencies=low
    - dependencies=high

matrix:
    allow_failures:
        - php: 7.0
        - php: hhvm

notifications:
    email: false

before_script:
    - composer self-update
    - if [ "$dependencies" = "lowest" ]; then composer update --prefer-lowest -n; fi
    - if [ "$dependencies" = "highest" ]; then composer update -n; fi;

script:
    - vendor/bin/phpunit
